language: node_js
node_js:
  - "8"
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
target_branch: master
before_script:
  - "yarn global add gh-pages"
  - "yarn global add gatsby"
script:
  - "yarn test"
  - "yarn build:prod"
after_success:
  - "yarn deploy"
